import esbuild from "esbuild";
import fs from "node:fs";
import { builtinModules } from "node:module";
import path from "node:path";

const production = process.argv.includes("--production");
const watch = process.argv.includes("--watch");
const deploy = process.argv.includes("--deploy");
const pluginId = "canvas-for-storyline";
const pluginsDir = process.env.OBSIDIAN_PLUGINS_DIR ?? "";
const releaseDir = "release";

function syncArtifacts() {
  fs.mkdirSync(releaseDir, { recursive: true });
  for (const file of ["main.js", "manifest.json", "styles.css"]) {
    fs.copyFileSync(file, path.join(releaseDir, file));
  }
  if (!deploy) return;
  if (!pluginsDir) throw new Error("OBSIDIAN_PLUGINS_DIR is required for deployment.");
  const target = path.basename(path.resolve(pluginsDir)) === pluginId
    ? path.resolve(pluginsDir)
    : path.join(path.resolve(pluginsDir), pluginId);
  fs.mkdirSync(target, { recursive: true });
  for (const file of ["main.js", "manifest.json", "styles.css"]) {
    fs.copyFileSync(path.join(releaseDir, file), path.join(target, file));
  }
  const marker = path.join(target, ".hotreload");
  if (!fs.existsSync(marker)) fs.writeFileSync(marker, "", "utf8");
  console.log(`[deploy] ${target}`);
}

const context = await esbuild.context({
  banner: { js: "/* Generated by esbuild. See the source repository. */" },
  entryPoints: ["src/main.ts"],
  outfile: "main.js",
  bundle: true,
  format: "cjs",
  platform: "node",
  target: "es2021",
  loader: { ".md": "text" },
  sourcemap: production ? false : "inline",
  minify: production,
  external: ["obsidian", "electron", ...builtinModules],
  logLevel: "info",
  plugins: [{
    name: "release-and-deploy",
    setup(build) {
      build.onEnd((result) => {
        if (result.errors.length === 0) syncArtifacts();
      });
    }
  }]
});

if (watch) {
  await context.watch();
  console.log("Watching Canvas for StoryLine sources …");
} else {
  await context.rebuild();
  await context.dispose();
}
