import { CATEGORY_LABELS, type StoryLineElement, type StoryLineProject } from "../../model/storyline";

export function renderMaster(project: StoryLineProject, elements: readonly StoryLineElement[]): string {
  const lines = [
    "<!-- Generated by Canvas for StoryLine. Manual changes may prevent automatic updates. -->",
    `# ${project.name} – Master`,
    "",
    "Diese Datei bündelt die ausgewählten StoryLine-Inhalte als Export-Basis.",
  ];
  for (const category of ["scenes", "sceneNotes", "characters", "locations"] as const) {
    const matching = elements.filter((element) => element.category === category);
    if (matching.length === 0) continue;
    lines.push("", `## ${CATEGORY_LABELS[category]}`, "");
    for (const element of matching) {
      lines.push(`### ${escapeHeading(element.title)}`, "", `![[${element.sourcePath}]]`, "");
    }
    if (lines[lines.length - 1] === "") lines.pop();
  }
  return `${lines.join("\n")}\n`;
}

function escapeHeading(value: string): string {
  return value.replace(/\r?\n/g, " ").trim();
}
